
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: teacher_portal_development

test:
  <<: *default
  database: see

production:
  <<: *default
  database: teacher_portal_production
  username: teacher_portal
  password: <%= ENV["TEACHER_PORTAL_DATABASE_PASSWORD"] %>
